[project]
name = "ComfyUI-geltz"
description = ""
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/geltz/ComfyUI-geltz"

[tool.comfy]
PublisherId = "geltz"
DisplayName = "ComfyUI-geltz"
Icon = ""
